**Theory part and info about NumPy**

Its a library that gives mathematical tools and functions used for manipulating shape and structure of data arrays.

At the beginning of a file we have to import it.

In [23]:
import numpy as np

**Array**

NumPy arrays (ndarray) are homogeneous so they can contain only elements of the same data type.

To create an array we can use the function np.array(...).

In [24]:
vector = np.array([1, 2, 3])
print(type(vector))
print(vector)

<class 'numpy.ndarray'>
[1 2 3]


Since these arrays are mutable like Python lists we can access them and modify elements using the indexing of each element, starting from 0.

In [25]:
print(vector[1])
vector[2] = 10
print(vector)

2
[ 1  2 10]


We can also use multidimensional arrays that are done like [row],[col]

In [26]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(type(matrix)) 
print(matrix[1,1])
print(matrix[:, 1])
print(matrix)

<class 'numpy.ndarray'>
5
[2 5 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


NumPy gives us a lot of useful functions to work and generate arrays.

In [30]:
a = np.zeros((2,2))
b = np.ones((1,2))
c = np.full((3,2), 7)
print(a)
print(b)
print(c)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]
 [7 7]]


We can see the dimension of a NumPy array accessing its .shape

In [32]:
print(a.shape)
print(b.shape)
print(c.shape)

(2, 2)
(1, 2)
(3, 2)


NumPy allows for fast algebraic operations on arrays, including element-wise addition, subtraction, multiplication, division, and dot products. These operations are much more efficient than using Python loops.

In [ ]:
vector = np.array([0, 1, 2, 3, 4, 5])

vector_sum1 = vector + 2
vector_sum2 = vector + vector   
vector_sub1 = vector - 6
vector_sub2 = vector_sum2 - vector
vector_scalar_prod = vector * 5
b = np.array([5, 4, 3, 2, 1, 0])
d_prod = vector.dot(b)
ew_prod = vector * b
vector_scalar_div = vector / 5

print(vector_sum1)
print(vector_sum2)
print(vector_sub1)
print(vector_sub2)
print(vector_scalar_prod)
print(d_prod)
print(ew_prod)
print(vector_scalar_div)

[2 3 4 5 6 7]
[ 0  2  4  6  8 10]
[-6 -5 -4 -3 -2 -1]
[0 1 2 3 4 5]
[ 0  5 10 15 20 25]
20
[0 4 6 6 4 0]
[0.  0.2 0.4 0.6 0.8 1. ]


NumPy provides a wide range of built-in functions to compute basic statistics on arrays,such as mean, standard deviation, min/max, median, and their corresponding indices.

In [35]:
vector = np.array([4, 1, 8, 2, 10, 30])

ave1 = np.mean(vector)
ave2 = vector.mean()
std1 = np.std(vector)
std2 = vector.std()
med1 = np.median(vector)
min1 = np.min(vector)
min2 = vector.min()
argmin1 = np.argmin(vector)
argmin2 = vector.argmin()
max1 = np.max(vector)
max2 = vector.max()
argmax1 = np.argmax(vector)
argmax2 = vector.argmax()

print(ave1)
print(ave2)
print(std1)
print(std2)
print(med1)
print(min1)
print(min2)
print(argmin1)
print(argmin2)
print(max1)
print(max2)
print(argmax1)
print(argmax2)

9.166666666666666
9.166666666666666
9.83898142876363
9.83898142876363
6.0
1
1
1
1
30
30
5
5
