**Theory part and info about NumPy**

Its a library that gives mathematical tools and functions used for manipulating shape and structure of data arrays.

At the beginning of a file we have to import it.

In [16]:
import numpy as np

**Array**

NumPy arrays (ndarray) are homogeneous so they can contain only elements of the same data type.

To create an array we can use the function np.array(...).

In [17]:
vector = np.array([1, 2, 3])
print(type(vector))
print(vector)

<class 'numpy.ndarray'>
[1 2 3]


Since these arrays are mutable like Python lists we can access them and modify elements using the indexing of each element, starting from 0.

In [18]:
print(vector[1])
vector[2] = 10
print(vector)

2
[ 1  2 10]


We can also use multidimensional arrays that are done like [row],[col]

In [21]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(type(matrix)) 
print(matrix[:, 1])
print(matrix)

<class 'numpy.ndarray'>
[2 5 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
