**<u>THEORY PART AND INFO ABOUT NUMPY<u>**

Its a library that gives mathematical tools and functions used for manipulating shape and structure of data arrays.

At the beginning of a file we have to import it.

In [1]:
import numpy as np # imports the NumPy library and gives it the alias 'np' for easier access

**Arrays**

NumPy arrays (`ndarray`) are homogeneous so they can contain only elements of the same data type.

To create an array we can use the function `np.array()`.

In [ ]:
vector = np.array([1, 2, 3]) # creates a 1D array (vector) with the values 1, 2, and 3

print(type(vector)) # prints the type of the variable 'vector'

print(vector)

<class 'numpy.ndarray'>
[1 2 3]


Since these arrays are mutable like Python lists we can access them and modify elements using the indexing of each element.

Counts starting from 0.

In [3]:
print(vector[1]) # prints the second element of the vector (index 1)
vector[2] = 10 # changes the third element of the vector (index 2) to 10

print(vector)

2
[ 1  2 10]


**Multidimensional arrays**

We can also use multidimensional arrays that are made like `[row],[col]`

In [4]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # creates a 3x3 array

print(type(matrix)) # prints the type of the variable 'matrix'
print(matrix[1,1]) # prints the element in the second row and second column of the matrix (index [1,1])
print(matrix[:, 1]) # prints all the elements in the second column of the matrix (index [:,1])
print(matrix)

<class 'numpy.ndarray'>
5
[2 5 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**NumPy functions**

NumPy gives us a lot of useful functions to work and generate arrays.

In [5]:
a = np.zeros((2,2)) # creates a 2x2 array filled with zeros
b = np.ones((1,2)) # creates a 1x2 array filled with ones
c = np.full((3,2), 7) # creates a 3x2 array filled with the value 7

print(a)
print(b)
print(c)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]
 [7 7]]


We can see the dimension of a NumPy array accessing its .shape

In [6]:
print(a.shape) # prints the shape of the array a
print(b.shape) # prints the shape of the array b
print(c.shape) # prints the shape of the array c

(2, 2)
(1, 2)
(3, 2)


NumPy allows for fast algebraic operations on arrays, including element-wise addition, subtraction, multiplication, division, and dot products. These operations are much more efficient than using Python loops.

In [ ]:
vector = np.array([0, 1, 2, 3, 4, 5])

vector_sum1 = vector + 2 # adds 2 to each element of the vector
vector_sum2 = vector + vector # adds the vector to itself
vector_sub1 = vector - 6 # subtracts 6 from each element of the vector
vector_sub2 = vector_sum2 - vector # subtracts the original vector from the sum
vector_scalar_prod = vector * 5 # multiplies each element of the vector by 5

b = np.array([5, 4, 3, 2, 1, 0])

d_prod = vector.dot(b) # computes the dot product of the vector and b
ew_prod = vector * b # computes the element-wise product of the vector and b
vector_scalar_div = vector / 5 # divides each element of the vector by 5

print(vector_sum1)
print(vector_sum2)
print(vector_sub1)
print(vector_sub2)
print(vector_scalar_prod)
print(d_prod)
print(ew_prod)
print(vector_scalar_div)

[2 3 4 5 6 7]
[ 0  2  4  6  8 10]
[-6 -5 -4 -3 -2 -1]
[0 1 2 3 4 5]
[ 0  5 10 15 20 25]
20
[0 4 6 6 4 0]
[0.  0.2 0.4 0.6 0.8 1. ]


NumPy provides a wide range of built-in functions to compute basic statistics on arrays,such as mean, standard deviation, min/max, median, and their corresponding indices.

In [8]:
vector = np.array([4, 1, 8, 2, 10, 30])

ave1 = np.mean(vector) # computes the mean of the vector
ave2 = vector.mean() # computes the mean of the vector using the method of the array
std1 = np.std(vector) # computes the standard deviation of the vector
std2 = vector.std() # computes the standard deviation of the vector using the method of the array
med1 = np.median(vector) # computes the median of the vector
min1 = np.min(vector) # computes the minimum value of the vector
min2 = vector.min() # computes the minimum value of the vector using the method of the array
argmin1 = np.argmin(vector) # computes the index of the minimum value of the vector
argmin2 = vector.argmin() # computes the index of the minimum value of the vector using the method of the array
max1 = np.max(vector) # computes the maximum value of the vector
max2 = vector.max() # computes the maximum value of the vector using the method of the array
argmax1 = np.argmax(vector) # computes the index of the maximum value of the vector
argmax2 = vector.argmax() # computes the index of the maximum value of the vector using the method of the array

print(ave1)
print(ave2)
print(std1)
print(std2)
print(med1)
print(min1)
print(min2)
print(argmin1)
print(argmin2)
print(max1)
print(max2)
print(argmax1)
print(argmax2)

9.166666666666666
9.166666666666666
9.83898142876363
9.83898142876363
6.0
1
1
1
1
30
30
5
5
